name: run jmeter on github action
description: automation with JMeter
author: Sebastian Boga <sebastian.boga@outlook.com>

runs:
  using: "composite"
  steps:
    - run: |
       java -version
       wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
       unzip apache-jmeter-5.6.3.zip
       cd apache-jmeter-5.6/bin
       ./jmeter -v
       pwd
       cd $GITHUB_WORKSPACE/apache-jmeter-5.6.3
       wget -q --no-check-certificate https://jmeter-plugins.org/files/packages/jpgc-dummy-0.4.zip  -P .
       unzip -o jpgc-dummy-0.4.zip  && rm jpgc-dummy-0.4.zip
       cd $GITHUB_WORKSPACE/apache-jmeter-5.6/bin
        for i in $( ls $GITHUB_WORKSPACE/*.jmx); do
           ./jmeter -n -t $i;
         done
      shell: bash


branding:
  color: green
  icon: power
